### PR TITLE
Add support for combinatorial member data

### PR DESCRIPTION
**Pull request by siewers**
Should be a fix for #1

### CODE REVIEW

**Review by AArnott — APPROVED** [review]
Looks fantastic. Thank you!

**Comment by AArnott** [comment]
This shipped in 1.5.2-beta to nuget.org.

**Comment by alrz** [comment]
Would this be available in dotnet-public?

**Comment by AArnott** [comment]
It's available on nuget.org. If you want it in any other feed, either set nuget.org as an upstream or copy the package over to that feed. I don't know anything about a `dotnet-public` feed.

**Pull request merged**
