### PR TITLE
Support CombinatorialMemberData for IEnumerable<string>

### LINKED ISSUE #54: CombinatorialMemberData for strings does not work
The following example throws an exception in xUnit:
```cs
public static readonly IEnumerable<string> StringFieldValues = Enumerable.Range(0, 5).Select(_ => Random.Next().ToString());

[Theory, CombinatorialData]
public void Test([CombinatorialMemberData(nameof(StringFieldValues))] string stringValue)
{
    Assert.True(true);
}
```

https://github.com/AArnott/Xunit.Combinatorial/blob/4b8210355b78548a73c191ea9b97fa81dc6c5de0/src/Xunit.Combinatorial/CombinatorialMemberDataAttribute.cs#L221-L225

The assertion should ensure that the member doesn't return `IEnumerable<object[]>`, which it doesn't, but it just seems to be wrong.

I guess an explicit check on whether the enumerated type is `object[]` would do the trick. I'm not completely sure what the condition _exactly_ tries to evaluate and it's a bit confusing to me.

I was probably the one who implemented support for combinatorial member data, so I can give it a shot on fixing this problem :)

By the way, xUnit throws `System.NotSupportedException : Specified method is not supported.`, which looks to be a bug also [reported here](https://github.com/xunit/xunit/issues/2555).

### PR DESCRIPTION
**Pull request by siewers**
Fixes #54

### CODE REVIEW

**Comment by siewers** [comment]
I don't know why the build fails. I changed the pinned .NET SDK version to 6.0.401, which is the latest .NET 6 version. Otherwise, I couldn't get it to build locally. I don't think it's the reason it fails though.

I decided to remove the check and test for non-generic `IEnumerable` return types, as the next error message clearly explains the return type should implement the generic `IEnumerable<T>`.

Besides that, I added explicit checks for `IEnumerable<T[]>` and `IEnumerable<IEnumerable<T>>`. I'm not sure if it's strictly necessary to split it, but I don't think it hurts to be explicit and return a descriptive message about any expected common mistakes the user might make.

**Comment by siewers** [comment]
@AArnott I know you might be busy, but this is blocking me from using this library at the moment. Would you be able to have a look? Thanks 🙂

**Comment by AArnott** [comment]
Yes, thank you for submitting the change. I'll take a look.

**Review by AArnott — APPROVED** [review]

**Comment by timba** [comment]
The latest stable version v1.5.25 doesn't include this fix. Any plans releasing it anytime soon?

**Comment by AArnott** [comment]
Published v1.6.24 to nuget.

**Pull request merged**
