### PR TITLE
Merge v1.7 for main

### PR DESCRIPTION
**Pull request by AArnott**

### CODE REVIEW

**Comment by AArnott** [comment]
@siewers, your recent #99 added tests that fail when run against main (which targets xunit v3). At least one reason I see is that the `TheoryData<T>` class from xunit v3 no longer implements `IEnumerable<object[]>`.

Would you be willing to investigate and push a branch that fixes this?

**Comment by siewers** [comment]
@AArnott Sure, I'll get right on it. I'm a bit confused, though. The project is now targeting .NET 9, but the tests still target .NET 8, is that on purpose or a mistake? In Rider, I'm getting warnings about it, so I'm not sure if I should update the tests to target .NET 9 as well?

**Comment by AArnott** [comment]
Thanks!

**Comment by siewers** [comment]
I see that xUnit 3 was only released 14 days ago. I haven't worked with version 3 yet, but many things have changed.
Is the plan to break compatibility with xUnit 2? If so, would it make more sense to bump the major version of Xunit.Combinatorial and let #99 merge into version 1.6 that targets xUnit 2?
I can then rework the implementation to target xUnit 3 in a separate branch.

**Comment by AArnott** [comment]
Yes, xunit 3 is new and quite the breaking change.
The `main` branch, which is the only one that targets xunit 3, already has had a major version bump to 2.0. 
Your change went into the v1.7 branch, which targets xunit 2 where it works today. 

Please consider this branch (the source branch for this PR) as the one where you can rework your change. Just send a PR that targets `v1.7_for_main` and I can complete it to fix _this_ PR.

**Comment by siewers** [comment]
Ah, okay, I think I understand now :)

I'm considering making the implementation only work with TheoryData<T> as that's also the recommended way of working with data sources in xUnit.

That would force the user to derive from TheoryData<T>, but I don't think that's a bad idea.

However, it would change a lot of tests. What do you think about that?

**Comment by AArnott** [comment]
Xunit v3 already puts some breaking change expense on the user. In principle then, I'm OK with requiring source changes for users that upgrade to the `main` branch of this repo.
And getting in step with the recommendations of xunit v3 is also generally a good thing.
We should definitely _support_ the recommended path.

That said, if we can continue to support the old way, so that the upgrade path for users is easier, that also seems worth doing if it isn't too much trouble. And at the moment, in main, that works. So I'm optimistic we can achieve it.

**Comment by siewers** [comment]
@AArnott, please review #125

**Pull request merged**
